---
- name: Configure new access-list on IOS-V devices
  hosts: "iosv-devices"
  gather_facts: false
  connection: local

  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    - name: configure new access list
      ios_config:
        lines:
          - 10 permit ip host 1.1.1.1 any log
          - 20 permit ip host 2.2.2.2 any log
        parents: ip access-list extended test
        before: no ip access-list extended test
        match: exact
        provider: "{{ cli }}"
      register: output

    - name: show output 
      debug:
        msg: '{{ output }}'

